import test from'node:test';import assert from'node:assert/strict';import{createAzureProposalGenerator}from'../lib/azure-remediation.mjs';
const config={ready:true,endpoint:'https://example-resource.openai.azure.com/openai/v1/',deployment:'fixture',key:'dummy-not-a-real-key'},context={revision:'fixture-revision',issue:{id:'f1',title:'Synthetic reliability concern'},sources:{'routes/example.ts':'const x = 1;\n'}};
const response=answer=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(answer)}}]}));
test('bounded proposal uses exact context without tools and returns only schema',async()=>{let sent;const propose=createAzureProposalGenerator(config,{fetchImpl:async(url,options)=>{sent=JSON.parse(options.body);assert.equal(options.redirect,'error');return response({revision:context.revision,diff:'fixture diff\n',rationale:'Review only',extra:'discarded'});}});const r=await propose(context);assert.equal(r.diff,'fixture diff\n');assert.equal(r.extra,undefined);assert.equal(sent.tools,undefined);assert.equal(sent.messages[1].content,JSON.stringify(context));});
test('abstention is explicit rather than an empty validated patch',async()=>{const result=await createAzureProposalGenerator(config,{fetchImpl:async()=>response({revision:context.revision,diff:'',rationale:'Missing control flow'})})(context);assert.equal(result.status,'abstained');assert.equal(result.rationale,'Missing control flow');assert.equal(result.diff,'');});
test('wrong revision, incomplete JSON and oversized responses are rejected',async()=>{await assert.rejects(createAzureProposalGenerator(config,{fetchImpl:async()=>response({revision:'wrong',diff:'x',rationale:'x'})})(context),/schema/);await assert.rejects(createAzureProposalGenerator(config,{fetchImpl:async()=>new Response('not JSON')})(context),/invalid JSON/);await assert.rejects(createAzureProposalGenerator(config,{fetchImpl:async()=>new Response('x'.repeat(131073))})(context),/size limit/);});
test('provider failure does not echo raw bodies or retry',async()=>{let calls=0;await assert.rejects(createAzureProposalGenerator(config,{fetchImpl:async()=>{calls++;return new Response('private-provider-detail',{status:429})}})(context),e=>e.message.includes('rate limited')&&!e.message.includes('private-provider-detail'));assert.equal(calls,1);});
test('safe provider error codes distinguish auth, refusal, length, schema and timeout without bodies',async()=>{const cases=[{code:'PROVIDER_AUTH',fetchImpl:async()=>new Response('PRIVATE AUTH BODY',{status:401})},{code:'PROVIDER_LENGTH',fetchImpl:async()=>new Response(JSON.stringify({choices:[{finish_reason:'length',message:{content:'PRIVATE TRUNCATED'}}]}))},{code:'PROVIDER_REFUSAL',fetchImpl:async()=>new Response(JSON.stringify({choices:[{message:{refusal:'PRIVATE REFUSAL'}}]}))},{code:'PROVIDER_SCHEMA',fetchImpl:async()=>response({revision:context.revision,diff:5,rationale:'x'})},{code:'PROVIDER_TIMEOUT',fetchImpl:async(_,options)=>new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(Error('PRIVATE TIMEOUT')),{once:true}))}];for(const c of cases){await assert.rejects(createAzureProposalGenerator(config,{fetchImpl:c.fetchImpl,timeoutMs:5})(context),e=>e.code===c.code&&!e.message.includes('PRIVATE'));}});
test('provider descriptor pins prompt/schema/deployment without credential material',()=>{const generator=createAzureProposalGenerator(config,{fetchImpl:async()=>{throw Error('not called')}});assert.equal(generator.descriptor.deployment,'fixture');assert.equal(generator.descriptor.promptHash.length,64);assert.ok(!JSON.stringify(generator.descriptor).includes(config.key));});
