import {mkdir,readFile,writeFile,rename,chmod} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
import {normalizeCapture,responseMetadata} from './traffic.mjs';
export const TARGET='http://127.0.0.1:3000';
export function allowed(raw){try{const u=new URL(raw);return u.origin===TARGET&&!u.username&&!u.password&&u.protocol==='http:';}catch{return false;}}
export function safeURL(raw){const u=new URL(raw);if(!allowed(raw))throw Error('Only the configured local storefront is allowed.');return u.origin+u.pathname.replace(/[^/]{100,}/g,'[omitted]');}
const now=()=>new Date().toISOString();
const LIMIT=1500;
export function routeCandidates(record,inventory){const path=new URL(record.url).pathname.split('/');return (inventory?.routes||[]).filter(r=>r.method===record.method&&r.path.split('/').length===path.length&&r.path.split('/').every((segment,i)=>segment.startsWith(':')?!!path[i]:segment===path[i])).map(r=>({method:r.method,path:r.path,file:r.file,line:r.line,status:'candidate'}));}
export class Capture {
 constructor({root=resolve('.runtime/capture'),chromium}={}){this.root=root;this.chromium=chromium;this.context=null;this.page=null;this.busy=false;this.frameBusy=false;this.pending=new Set();this.persistQueue=Promise.resolve();this.records=[];this.state='stopped';this.blocked=0;this.dropped=0;this.startedAt=null;this.stoppedAt=null;this.sessionId=null;this.inventory={routes:[]};}
 async init(){try{this.inventory=JSON.parse(await readFile(new URL('../fixtures/storefront-routes.json',import.meta.url),'utf8'));}catch{}await mkdir(this.root,{recursive:true,mode:0o700});await chmod(this.root,0o700);try{const s=JSON.parse(await readFile(resolve(this.root,'capture.json'),'utf8'));this.records=s.records||[];this.sessionId=s.sessionId;this.startedAt=s.startedAt;this.stoppedAt=s.stoppedAt;this.blocked=s.blocked||0;this.dropped=s.dropped||0;this.state=s.state==='recording'?'interrupted':s.state;}catch(e){if(e.code!=='ENOENT')throw Error('Saved capture unreadable; preserved for recovery.');}return this;}
 status(){return {state:this.state,sessionId:this.sessionId,startedAt:this.startedAt,stoppedAt:this.stoppedAt,count:this.records.length,blocked:this.blocked,dropped:this.dropped,failedBodies:this.records.filter(r=>r.bodyState==='failed').length,origin:TARGET,viewport:{width:1280,height:800},limit:LIMIT,browserOpen:!!this.context};}
 snapshot(){return {...this.status(),schemaVersion:1,provenance:'Observed by dedicated local Playwright browser; no replay or security verification.',records:this.records.map(r=>({...r,sourceCandidates:routeCandidates(r,this.inventory)})),sourceInventory:{...this.inventory,unvisitedRoutes:this.inventory.routes.filter(route=>!this.records.some(r=>routeCandidates(r,{routes:[route]}).length))},limitations:['HTTP-level observations only: raw packets, WebSocket frames, downloads and service-worker traffic are not recorded.','Only visited browser flows are covered.','Queries, fragments, headers, request bodies and response values are excluded.','JSON structure samples are limited to 64 KB and allowlisted keys.','External requests, popup windows, service workers and downloads are blocked.','Source matches are candidates only; no security proof is produced.']};}
 persist(){const text=JSON.stringify(this.snapshot(),null,2);this.persistQueue=this.persistQueue.then(async()=>{await writeFile(resolve(this.root,'capture.json.tmp'),text,{mode:0o600});await rename(resolve(this.root,'capture.json.tmp'),resolve(this.root,'capture.json'));});return this.persistQueue;}
 async start(){if(this.busy)throw Error('Browser lifecycle operation in progress.');if(this.context)return this.status();this.busy=true;try{
 if(!this.chromium){const spec=process.env.XANDER_PLAYWRIGHT_MODULE;this.chromium=(await import(spec?pathToFileURL(resolve(spec)).href:'playwright')).chromium;}
 this.context=await this.chromium.launchPersistentContext(resolve(this.root,'browser-profile'),{headless:true,chromiumSandbox:true,viewport:{width:1280,height:800},serviceWorkers:'block',acceptDownloads:false,...(process.env.XANDER_CHROMIUM?{executablePath:process.env.XANDER_CHROMIUM}:{})});
 const ctx=this.context;
 // Authentication depends on tab-scoped basket state; never reuse a token without a fresh login.
 await ctx.clearCookies({name:'token'});
 await ctx.addInitScript(()=>{if(location.origin==='http://127.0.0.1:3000'&&!sessionStorage.getItem('bid')){localStorage.removeItem('token');localStorage.removeItem('totp_tmp_token');document.cookie='token=; Max-Age=0; path=/';}});
 this.sessionId=this.sessionId||randomUUID();this.startedAt=now();this.stoppedAt=null;this.state='recording';
 await ctx.route('**/*',route=>{if(allowed(route.request().url()))return route.continue();this.blocked++;return route.abort('blockedbyclient');});
 if(ctx.routeWebSocket)await ctx.routeWebSocket('**/*',route=>{const u=new URL(route.url());if(u.protocol==='ws:'&&u.host==='127.0.0.1:3000')route.connectToServer();else{this.blocked++;route.close();}});
 for(const p of ctx.pages())await p.close();this.page=await ctx.newPage();
 ctx.on('page',p=>{if(p!==this.page){this.blocked++;p.close().catch(()=>{});}});
 this.page.on('framenavigated',frame=>{if(frame===this.page?.mainFrame()&&!allowed(frame.url())&&frame.url()!=='about:blank'){this.blocked++;this.page.close().catch(()=>{});}});
 this.page.on('download',d=>d.cancel());this.page.on('dialog',d=>d.dismiss());
 const ids=new WeakMap();
 ctx.on('request',req=>{if(this.state!=='recording'||!allowed(req.url()))return;if(this.records.length>=LIMIT){this.dropped++;return;}const record={captureRequestId:randomUUID(),method:req.method(),resourceType:req.resourceType(),url:safeURL(req.url()),status:null,observedAt:now(),responseObserved:false,evidenceStatus:'observed',sourceMatchStatus:'candidate-unmatched',bodyState:'pending',responseMetadata:responseMetadata(),sessionId:this.sessionId};ids.set(req,record);this.records.push(record);});
 ctx.on('response',res=>{const r=ids.get(res.request());if(!r)return;const work=(async()=>{r.status=res.status();r.responseObserved=true;const mime=res.headers()['content-type']||'';r.bodyState=(r.status===204||res.request().method()==='HEAD')?'empty':'not-sampled';r.responseMetadata=responseMetadata({contentType:mime},'project67-jsonl');if(mime.includes('json')){try{const size=Number(res.headers()['content-length']);if(size>65536){r.bodyState='too-large';return;}const body=await res.body();if(body.length===0){r.bodyState='empty';return;}if(body.length>65536){r.bodyState='too-large';return;}r.responseMetadata=responseMetadata({contentType:mime,body:body.toString(),bodySaved:{bytes:body.length}},'project67-jsonl');r.bodyState=r.responseMetadata.schema?'sampled-structure':'unparseable';}catch{r.bodyState='failed';}}})().finally(()=>{this.pending.delete(work);this.persist().catch(()=>{this.state='storage-error';});});this.pending.add(work);});
 ctx.on('requestfailed',req=>{const r=ids.get(req);if(r){r.bodyState='failed';this.persist().catch(()=>{this.state='storage-error';});}});
 ctx.on('close',()=>{if(this.context===ctx){this.context=null;this.page=null;this.state='stopped';this.stoppedAt=now();this.persist().catch(()=>{});}});
 await this.page.goto(TARGET,{waitUntil:'domcontentloaded',timeout:30000});await this.persist();return this.status();
 }catch(e){if(this.context)await this.context.close().catch(()=>{});this.context=null;this.page=null;this.state='error';await this.persist();throw Error('Controlled browser could not start. Check local storefront and browser installation.');}finally{this.busy=false;}}
 async stop(){if(this.busy)throw Error('Browser lifecycle operation in progress.');this.busy=true;try{this.state='stopping';if(this.context)await this.context.close();await Promise.allSettled([...this.pending]);this.context=null;this.page=null;this.state='stopped';this.stoppedAt=now();await this.persist();return this.status();}finally{this.busy=false;}}
 async navigate(url){if(!allowed(url))throw Error('Only the configured local storefront is allowed.');if(!this.page)throw Error('Launch browser first.');await this.page.goto(url,{waitUntil:'domcontentloaded'});}
 async frame(){if(!this.page)throw Error('Browser is stopped.');if(this.frameBusy)throw Error('Frame pending.');this.frameBusy=true;try{return await this.page.screenshot({type:'jpeg',quality:65});}finally{this.frameBusy=false;}}
 async input(data){if(!this.page)throw Error('Launch browser first.');if(data.type==='click'){if(!Number.isFinite(data.x)||!Number.isFinite(data.y)||data.x<0||data.x>=1280||data.y<0||data.y>=800)throw Error('Invalid pointer position.');await this.page.mouse.click(data.x,data.y);}else if(data.type==='text'){if(typeof data.text!=='string'||data.text.length>500)throw Error('Text limit is 500 characters.');await this.page.keyboard.insertText(data.text);}else if(data.type==='key'){if(!['Enter','Tab','Shift+Tab','Backspace','Delete','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape','Space','Control+A'].includes(data.key))throw Error('Unsupported key.');await this.page.keyboard.press(data.key);}else if(data.type==='wheel'){if(!Number.isFinite(data.dy)||Math.abs(data.dy)>1000)throw Error('Invalid scroll.');await this.page.mouse.wheel(0,data.dy);}else throw Error('Unsupported input.');}
 har(){return {log:{version:'1.2',creator:{name:'Xander ordinary browser recorder',version:'1'},entries:this.records.map(r=>({_requestId:r.captureRequestId,startedDateTime:r.observedAt,request:{method:r.method,url:r.url,headers:[],queryString:[]},response:{status:r.status||0,headers:[],content:{mimeType:r.responseMetadata.contentType||'',size:r.responseMetadata.bytes||0}},_evidenceStatus:'observed',_bodyOmitted:true}))}};}
 normalized(){const n=normalizeCapture({format:'har',content:this.har()});for(let i=0;i<n.traffic.length;i++)n.traffic[i].responseMetadata=this.records[i].responseMetadata;return {...n,provenance:'Local observed capture',securityVerification:'none'};}
}
export async function createCaptureHandler(options={}){
 const capture=await new Capture(options).init();
 const handler=async(req,res,path)=>{if(!path.startsWith('/api/capture/'))return false;const send=(code,data)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{
 if(req.method==='GET'&&path==='/api/capture/coverage'){send(200,JSON.parse(await readFile(new URL('../fixtures/capture-coverage.json',import.meta.url),'utf8')));return true;}
 if(req.method==='GET'&&path==='/api/capture/status'){send(200,{...capture.status(),recent:capture.records.slice(-30).map(r=>({...r,sourceCandidates:routeCandidates(r,capture.inventory)}))});return true;}
 if(req.method==='GET'&&path==='/api/capture/export'){res.setHeader('Content-Disposition','attachment; filename="xander-observed-capture.json"');send(200,{...capture.snapshot(),normalized:capture.normalized()});return true;}
 if(req.method==='GET'&&path==='/api/capture/har'){res.setHeader('Content-Disposition','attachment; filename="xander-observed.har"');send(200,capture.har());return true;}
 if(req.method==='GET'&&path==='/api/capture/frame'){const frame=await capture.frame();res.writeHead(200,{'Content-Type':'image/jpeg','Cache-Control':'no-store'});res.end(frame);return true;}
 if(req.method!=='POST')throw Error('Unsupported capture route.');if(!String(req.headers['content-type']).startsWith('application/json'))throw Error('Use application/json.');let text='';for await(const part of req){text+=part;if(Buffer.byteLength(text)>4096)throw Error('Input too large.');}const body=JSON.parse(text||'{}');
 if(path==='/api/capture/start')send(200,await capture.start());else if(path==='/api/capture/stop')send(200,await capture.stop());else if(path==='/api/capture/input'){await capture.input(body);send(200,{ok:true});}else if(path==='/api/capture/navigate'){await capture.navigate(body.url);send(200,{ok:true});}else throw Error('Unsupported capture route.');
 }catch(e){send(400,{error:e.message});}return true;};handler.capture=capture;return handler;
}
