import {inferRole,fail} from './extract.mjs';
const money=value=>{if(!/^\d{1,12}(\.\d{1,2})?$/.test(String(value)))return null;return Math.round(Number(value)*100);};
export function citation(file,ref={}){const originalRow=ref.rowStart;const position=file.rowNumbers&&originalRow?{...ref,recordStart:originalRow,rowStart:file.rowNumbers[originalRow-1],rowEnd:file.rowNumbers[(ref.rowEnd??originalRow)-1]}:ref;return {fileId:file.id,fileName:file.name,scope:file.scope,folderId:file.folderId,sourceType:'observed-in-file',...(file.sheet?{sheet:file.sheet}:{}),...position,previewUrl:`/vault.html?file=${file.id}${originalRow?'&row='+originalRow:''}${file.sheet?'&sheet='+encodeURIComponent(file.sheet):''}${ref.chunkIndex!==undefined?'&chunk='+ref.chunkIndex:''}`};}
async function* datasets(files,load){for(const file of files){const data=await load(file);if(data.kind==='workbook'){for(const sheet of data.sheets)yield {file:{...file,sheet:sheet.name,rowNumbers:sheet.rowNumbers,mapping:file.sheetMappings?.[sheet.name]},data:sheet};}else yield {file,data};}}
const chunkRef=(chunk,index)=>{const {text,...ref}=chunk;return {...ref,chunkIndex:index};};
export function* records(data,file){const mapping=file.mapping?.fields??{};const names=data.columns.map(x=>x.toLowerCase().replace(/[ -]/g,'_'));for(let i=0;i<data.rows.length;i++){const row=data.rows[i];const record=Object.create(null);names.forEach((c,n)=>record[c]=row[n]);for(const [canonical,column]of Object.entries(mapping))record[canonical]=row[data.columns.indexOf(column)];yield {record,row:i+1};}}
export async function buildKnowledge(files,load,scope,version){
 const active=files.filter(f=>f.scope===scope&&!f.deletedAt),tables=[],facts=[],gaps=[],conflicts=[],currencies=new Map(),orders=new Map(),customerIds=new Set(),productIds=new Set(),productCategory=new Map(),items=[],refundEntries=[],sources=[];let invalid=0,duplicates=0;
 const currency=(code)=>{if(!currencies.has(code))currencies.set(code,{currency:code,completedOrderCount:0,grossMinor:0,refundMinor:0,customers:new Set(),minDate:null,maxDate:null,months:new Map(),productMix:new Map()});return currencies.get(code);};
 for await(const {file,data} of datasets(active,load)){if(data.kind==='text')for(const [chunkIndex,chunk] of data.chunks.slice(0,2).entries())facts.push({category:file.category??'Business documents',text:chunk.text.slice(0,900),sourceType:'observed-in-file',source:citation(file,chunkRef(chunk,chunkIndex))});if(data.kind!=='table')continue;
 const role=file.mapping?.role??inferRole(data.columns);tables.push({fileId:file.id,fileName:file.name,sheet:file.sheet??null,role,roleSourceType:file.mapping?'owner-asserted':'inferred',mapping:file.mapping??null,rowCount:data.rows.length,columns:data.columns});const source=citation(file,{rowStart:1,rowEnd:data.rows.length});sources.push({...source,role});if(!role)continue;
 for(const {record:r,row}of records(data,file)){
 if(role==='orders'){
 if(!r.order_id||orders.has(r.order_id)){duplicates++;continue;}
 const total=money(r.total),validDate=/^\d{4}-\d{2}-\d{2}$/.test(r.order_date)&&!Number.isNaN(Date.parse(r.order_date))&&new Date(r.order_date).toISOString().slice(0,10)===r.order_date;
 if(total===null||!validDate||!r.customer_id||!(/^[A-Z]{3}$/).test(r.currency??'')||!r.status){invalid++;continue;}
 const entry={...r,totalMinor:total,source:citation(file,{rowStart:row,rowEnd:row})};orders.set(r.order_id,entry);
 if(['completed','paid','delivered','shipped'].includes(r.status.toLowerCase())){const c=currency(r.currency);entry.recognized=true;c.completedOrderCount++;c.grossMinor+=total;c.customers.add(r.customer_id);c.minDate=c.minDate&&c.minDate<r.order_date?c.minDate:r.order_date;c.maxDate=c.maxDate&&c.maxDate>r.order_date?c.maxDate:r.order_date;c.months.set(r.order_date.slice(0,7),(c.months.get(r.order_date.slice(0,7))??0)+total);}
 }else if(role==='customers'){if(r.customer_id)customerIds.add(r.customer_id);}else if(role==='products'){if(r.product_id){productIds.add(r.product_id);productCategory.set(r.product_id,r.category||'Uncategorized');}}else if(role==='refunds')refundEntries.push({r,file,row});else if(role==='order_items')items.push({r,file,row});
 }
 }
 const refundIds=new Set();let orphanRefunds=0,orphanItems=0;
 for(const {r}of refundEntries){if(r.status?.toLowerCase()!=='settled')continue;const amount=money(r.refund_amount),o=orders.get(r.order_id);if(!r.refund_id||refundIds.has(r.refund_id)){duplicates++;continue;}refundIds.add(r.refund_id);if(amount===null||!o?.recognized||o.currency!==r.currency){orphanRefunds++;continue;}currency(r.currency).refundMinor+=amount;}
 for(const {r}of items){const o=orders.get(r.order_id);if(!o){orphanItems++;continue;}if(!o.recognized)continue;const total=money(r.line_total),qty=Number(r.quantity);if(total===null||!Number.isInteger(qty)||qty<=0||r.currency!==o.currency){invalid++;continue;}const cat=productCategory.get(r.product_id)||r.product_id||'Unknown product';const mix=currency(o.currency).productMix;const prior=mix.get(cat)??{category:cat,quantity:0,grossMinor:0};prior.quantity+=qty;prior.grossMinor+=total;mix.set(cat,prior);}
 if(duplicates)conflicts.push(`${duplicates} duplicate or missing identifiers were excluded. First encountered order/refund identifier wins; review overlapping imports.`);if(invalid)conflicts.push(`${invalid} malformed financial records were excluded; required dates, amounts, currencies or quantities failed validation.`);if(orphanRefunds)conflicts.push(`${orphanRefunds} settled refund records could not be matched to recognized orders in the same currency and were excluded.`);if(orphanItems)conflicts.push(`${orphanItems} order items have no matching valid order.`);
 if(!orders.size)gaps.push('No recognized orders table. Map order_id, order_date, customer_id, total, currency and status to compute financial aggregates.');if(!refundEntries.length)gaps.push('No refunds ledger; zero observed refunds does not establish that refunds were zero.');if(!customerIds.size)gaps.push('No customer register has been recognized.');if(!productIds.size)gaps.push('No product register has been recognized.');gaps.push('Costs, margin, tax components and cash flow are unknown.','Incident likelihood, causal loss and forecasts are unknown.','Document statements are not independently verified; contradictory policies need owner review.');
 const financials=[...currencies.values()].map(c=>{if(!Number.isSafeInteger(c.grossMinor)||!Number.isSafeInteger(c.refundMinor))throw fail('Financial aggregate exceeds supported exact arithmetic range.',422);const days=c.minDate?Math.round((Date.parse(c.maxDate)-Date.parse(c.minDate))/86400000)+1:0;return {currency:c.currency,completedOrderCount:c.completedOrderCount,grossRevenue:c.grossMinor/100,refundAmount:c.refundMinor/100,netRecordedSales:(c.grossMinor-c.refundMinor)/100,meanOrderValue:c.completedOrderCount?c.grossMinor/100/c.completedOrderCount:null,activeCustomers:c.customers.size,dateRange:{from:c.minDate,to:c.maxDate,inclusiveDays:days},grossRevenuePerDay:days?c.grossMinor/100/days:null,monthlyRevenue:[...c.months].sort().map(([month,value])=>({month,grossRevenue:value/100})),productMix:[...c.productMix.values()].map(m=>({...m,grossRevenue:m.grossMinor/100,grossMinor:undefined})),sourceType:'derived',sources:sources.filter(s=>['orders','refunds','order_items','products'].includes(s.role))};});
 return {snapshotVersion:version,scope,synthetic:scope==='demo',localOnly:true,synthesis:'Deterministic extraction and arithmetic. No LLM synthesis has run.',counts:{files:active.length,indexedFiles:active.filter(x=>x.status==='indexed').length,tableRows:tables.reduce((s,x)=>s+x.rowCount,0),orders:orders.size,customers:customerIds.size,products:productIds.size},definitions:{grossRevenue:'Sum of total for orders with status completed, paid, delivered or shipped; pending/cancelled excluded. Amounts aggregated in integer minor units, currencies never combined.',netRecordedSales:'Recognized gross revenue minus matched settled refunds; not profit or cash flow.',meanOrderValue:'Recognized gross revenue divided by recognized order count.',grossRevenuePerDay:'Recognized gross revenue divided by inclusive calendar days between earliest and latest recognized order dates.',tableRows:'Every parsed record across active tables, not preview rows.'},financials,facts,tables,gaps,conflicts,assumptionSuggestions:financials.map(c=>({key:'dailyRevenue',value:c.grossRevenuePerDay,unit:c.currency+'/day',sourceType:'derived',definition:'Historical average gross revenue per inclusive calendar day; not a forecast.',snapshotVersion:version,sources:c.sources.filter(x=>x.role==='orders'),requiresOwnerConfirmation:true})),unknownAssumptions:['incidentLikelihood','lossFraction','recoveryTime','profitMargin']};
}
export async function searchKnowledge(files,load,scope,query,limit=20){const tokens=query.toLowerCase().match(/[\p{L}\p{N}_@.\-]+/gu)?.slice(0,12)??[];if(!tokens.length)return [];const matches=[];const consider=(text,source)=>{const lower=text.toLowerCase();if(!tokens.every(t=>lower.includes(t)))return;let score=tokens.reduce((s,t)=>s+(lower.split(t).length-1),0);matches.push({text:text.slice(0,1600),source,score});matches.sort((a,b)=>b.score-a.score);if(matches.length>limit)matches.pop();};for await(const {file,data} of datasets(files.filter(f=>f.scope===scope&&!f.deletedAt),load)){for(const [chunkIndex,chunk]of data.chunks.entries())consider(chunk.text,citation(file,chunkRef(chunk,chunkIndex)));if(data.kind==='table')data.rows.forEach((row,i)=>consider(data.columns.map((c,n)=>`${c}: ${row[n]}`).join(' | '),citation(file,{rowStart:i+1,rowEnd:i+1})));}return matches;}
