import{readFile,stat,mkdir,writeFile,rename,unlink,readdir}from'node:fs/promises';import{randomUUID,createHash}from'node:crypto';
const fail=(message,status=400,code='REQUEST_INVALID')=>Object.assign(new Error(message),{status,code});
const send=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
const canonical=value=>value===null||typeof value!=='object'?JSON.stringify(value):Array.isArray(value)?'['+value.map(canonical).join(',')+']':'{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';
const hash=value=>createHash('sha256').update(canonical(value)).digest('hex');
const SAFE_CODES=new Set(['PROVIDER_UNAVAILABLE','CONTEXT_LIMIT','PROVIDER_RATE_LIMIT','PROVIDER_AUTH','PROVIDER_HTTP_ERROR','PROVIDER_BODY','PROVIDER_SIZE','PROVIDER_JSON','PROVIDER_LENGTH','PROVIDER_REFUSAL','PROVIDER_SCHEMA','PROVIDER_TIMEOUT','PROVIDER_CONNECTION']);
const errorInfo=e=>e.code==='INVALID_PROPOSAL'?{code:'INVALID_DIFF',message:e.message}:SAFE_CODES.has(e.code)?{code:e.code,message:e.message}:{code:'PROPOSAL_FAILED',message:'Proposal operation failed. No source was changed.'};
export async function createRemediationHandler({reviewer,runDirs,dataDir,ready=false}){
 await mkdir(dataDir,{recursive:true,mode:0o700});let activeKey=null;const records=new Map(),legacy=[];
 async function persist(record){const target=dataDir+'/'+record.key+'.json',temp=target+'.'+randomUUID()+'.tmp';try{await writeFile(temp,JSON.stringify(record,null,2)+'\n',{mode:0o600,flag:'wx'});await rename(temp,target);}finally{await unlink(temp).catch(()=>{});}}
 for(const name of await readdir(dataDir)){if(!/^(?:[a-f0-9]{64}|[a-f0-9-]{36})\.json$/.test(name))continue;try{if((await stat(dataDir+'/'+name)).size>250000)continue;const saved=JSON.parse(await readFile(dataDir+'/'+name,'utf8'));if(saved.schemaVersion==='remediation-cache-v1'&&name===saved.key+'.json'){if(saved.status==='generating'){saved.status='failed';saved.error={code:'INTERRUPTED',message:'Server restarted during proposal generation. Retry explicitly; no automatic request was made.'};saved.updatedAt=new Date().toISOString();await persist(saved);}records.set(saved.key,saved);}else if(saved.runId&&saved.issueId&&saved.status==='proposed')legacy.push(saved);}catch{}}
 async function loadRun(id){for(const dir of runDirs){const p=dir+'/'+id+'.json';try{if((await stat(p)).size>40000000)throw fail('Saved run is outside proposal bounds.',413);const run=JSON.parse(await readFile(p,'utf8'));if(run.id===id)return run;}catch(e){if(e.code==='ENOENT')continue;throw e;}}throw fail('Run not found.',404);}
 function historical(runId,issueId,key){return [...legacy.filter(p=>p.runId===runId&&p.issueId===issueId).map(proposal=>({proposal,freshness:'legacy-unverified',reason:'Saved proposal predates model/prompt cache identity. Available for historical review only; not a current-key cache hit.'})),...[...records.values()].filter(r=>r.key!==key&&r.runId===runId&&r.issueId===issueId&&r.proposal).map(r=>({proposal:r.proposal,freshness:'stale',reason:'Saved source, finding or provider/prompt identity differs from the current context.',cacheKey:r.key}))].slice(-5);}
 const cacheSummary=record=>record?{key:record.key,status:record.status,createdAt:record.createdAt,updatedAt:record.updatedAt,error:record.error??null,reason:record.status==='abstained'?record.proposal?.rationale:null,attempts:record.attempts,identity:record.identity}:null;
 async function prepare(runId,findingId){const run=await loadRun(runId);if(!['completed','partial'].includes(run.status))throw fail('Select an assessed result before generating a proposal.',409);const finding=run.result?.findings?.find(f=>f.id===findingId);if(!finding)throw fail('Finding not found.',404);
 const evidence=[...(run.context?.evidence??[]),...(run.context?.batches??[]).flatMap(b=>b.evidence??[])],byId=new Map(evidence.map(e=>[e.id,e]));const refs=(finding.citationIds??[]).flatMap(id=>byId.get(id)?.sources??[]).filter(s=>typeof s.path==='string');const issue={id:finding.id,title:finding.title,description:finding.description??'',mechanism:finding.mechanism??'',remediation:finding.remediation??'',status:finding.status,sourceRefs:refs};const sourceFiles=[...new Set(refs.map(r=>r.path))];let context;
 try{context=await reviewer.prepare({issue});}catch(e){const reason=e.code==='INVALID_PROPOSAL'?e.message:'Pinned source context is unavailable.';return{run,issue,blocked:true,response:{cache:{status:'blocked',key:null,reason},proposal:null,historicalProposals:historical(runId,findingId,null),eligibility:{eligible:false,reason,sourceFileCount:sourceFiles.length,sourceFiles,maxSupportFiles:8,maxModifiedFiles:4,contextPlan:{status:'needs-context',policy:'preserve-all-cited-support-files',supportFiles:sourceFiles,automaticSubset:false,splitRequired:sourceFiles.length>8||/bound|too large|transfer limit/.test(reason),nextStep:'Resolve source validation or define dependency-complete smaller issue boundaries for owner review. No cited files have been silently dropped or sent.'}},providerReady:ready}};}
 const identity={cacheSchema:'remediation-cache-v1',reviewSchema:'pinned-visible-diff-support-v3',sourceRevision:context.revision,sourceRefs:context.sourceRefs.slice().sort((a,b)=>a.path.localeCompare(b.path)),allowedRangesHash:hash(context.allowedLineRanges),findingHash:hash(issue),proposalIdentity:reviewer.capabilities().proposalIdentity??{provider:'unknown',schemaVersion:'unknown'}};
 const key=hash(identity),record=records.get(key),history=historical(runId,findingId,key);const response={cache:cacheSummary(record)??{key,status:history.length?'stale':'missing',reason:history.length?'Historical proposal available; freshness is not established for the current source/finding/provider context.':null},proposal:record?.proposal??null,historicalProposals:history,eligibility:{eligible:true,reason:null,sourceFileCount:sourceFiles.length,sourceFiles,contextBytes:Buffer.byteLength(JSON.stringify(context)),supportScope:context.supportScope??null,maxSupportFiles:8,maxModifiedFiles:4},providerReady:ready};return{run,issue,key,identity,record,response};}
 return async(req,res)=>{const p=new URL(req.url,'http://localhost').pathname,match=p.match(/^\/api\/workspace\/(?:v2\/)?runs\/([a-f0-9-]{36})\/findings\/([A-Za-z0-9_-]{1,100})\/fix$/);if(p!=='/api/remediation/status'&&!match)return false;
 try{if(p==='/api/remediation/status'&&req.method==='GET'){send(res,200,{...reviewer.capabilities(),ready,active:!!activeKey,cacheSchema:'remediation-cache-v1',automaticCalls:false,limits:['Only supported cited public application files can be proposed.','Proposals are not applied or tested.','Cached proposals require matching source, issue and model/prompt identity.']});return true;}if(!match||!['GET','POST'].includes(req.method))throw fail('Route not found.',404);
 if(req.method==='POST'&&(req.headers['sec-fetch-site']==='cross-site'||(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)))throw fail('Cross-origin request rejected.',403);
 let body={};if(req.method==='POST'){if(!String(req.headers['content-type']??'').startsWith('application/json'))throw fail('Send application/json.',415);let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>4096)throw fail('Request exceeds 4 KiB.',413);chunks.push(Buffer.from(c));}try{body=JSON.parse(Buffer.concat(chunks).toString());}catch{throw fail('Invalid JSON.');}if(body.consent!==true)throw fail('Explicit consent is required.');}
 const state=await prepare(match[1],match[2]);if(req.method==='GET'){send(res,200,state.response);return true;}if(state.blocked){send(res,422,{...state.response,error:state.response.eligibility.reason,code:'CONTEXT_INELIGIBLE'});return true;}
 // Re-read after asynchronous preparation: concurrent requests may have created this key.
 const existing=records.get(state.key);if(existing?.status==='generating'){send(res,202,{...state.response,cache:cacheSummary(existing)});return true;}if(existing&&(['proposed'].includes(existing.status)||body.retry!==true)){send(res,200,{...state.response,cache:cacheSummary(existing),proposal:existing.proposal??null,cached:true});return true;}
 if(activeKey)throw fail('Another proposal is being generated. Wait for it to finish.',409,'PROPOSAL_BUSY');if(!ready){send(res,503,{...state.response,error:'Proposal provider is not configured. Existing historical proposals remain available.',code:'PROVIDER_UNAVAILABLE'});return true;}
 activeKey=state.key;const record={schemaVersion:'remediation-cache-v1',key:state.key,id:existing?.id??randomUUID(),runId:state.run.id,issueId:state.issue.id,status:'generating',identity:state.identity,createdAt:existing?.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString(),attempts:(existing?.attempts??0)+1,error:null,proposal:null};records.set(record.key,record);
 try{await persist(record);let proposal;try{proposal=await reviewer.propose({issue:state.issue,consent:true});record.status=proposal.status==='abstained'?'abstained':'proposed';record.proposal={...proposal,id:record.id,runId:record.runId,createdAt:new Date().toISOString(),cacheKey:record.key};}catch(e){record.status='failed';record.error=errorInfo(e);}record.updatedAt=new Date().toISOString();await persist(record);send(res,200,{...state.response,cache:cacheSummary(record),proposal:record.proposal,cached:false});}catch{record.status='failed';record.error={code:'PERSISTENCE_FAILED',message:'Proposal cache could not be saved. No source was changed.'};send(res,500,{error:record.error.message,code:record.error.code});}finally{activeKey=null;}return true;
 }catch(e){send(res,e.status??500,{error:e.status?e.message:'Proposal operation failed. No source was changed.',code:e.status?e.code:'PROPOSAL_FAILED'});return true;}
 };
}
