// Reproducible fictional business corpus. No network access and no random state.
export const SEED_VERSION='juice-shop-2026-v2';
export function* seedCorpus(){
 const products=Array.from({length:500},(_,i)=>({id:`P${String(i+1).padStart(4,'0')}`,name:`JuiceShop ${['Cold-pressed juice','Smoothie','Snack','Bundle','Merchandise'][i%5]} ${i+1}`,category:['Cold-pressed juice','Smoothie','Snack','Bundle','Merchandise'][i%5],price:199+(i%80)*25}));
 yield {folder:'Product',name:'products.csv',body:'product_id,name,category,price,currency\n'+products.map(p=>`${p.id},${p.name},${p.category},${p.price}.00,INR`).join('\n')};
 yield {folder:'Customers',name:'customers.csv',body:'customer_id,name,email,segment,city\n'+Array.from({length:20000},(_,i)=>`C${String(i+1).padStart(5,'0')},Fictional Customer ${i+1},customer${i+1}@example.com,${['Retail','Small business','Wholesale'][i%3]},${['Pune','Delhi','Bengaluru','Mumbai'][i%4]}`).join('\n')};
 const orders=['order_id,order_date,customer_id,total,currency,status'],items=['order_id,product_id,quantity,unit_price,line_total,currency'],refunds=['refund_id,order_id,refund_date,refund_amount,currency,status'],support=['ticket_id,order_id,category,status'];
 const start=Date.UTC(2024,9,1);let gross=0,refundTotal=0,paidCount=0;
 for(let i=0;i<100000;i++){const id=`O${String(i+1).padStart(6,'0')}`,p=products[i%500],q=1+i%3,total=p.price*q,day=Math.floor(i*730/100000),date=new Date(start+day*86400000).toISOString().slice(0,10),status=i%20===0?'cancelled':i%20===1?'pending':'completed';orders.push(`${id},${date},C${String(i%20000+1).padStart(5,'0')},${total}.00,INR,${status}`);items.push(`${id},${p.id},${q},${p.price}.00,${total}.00,INR`);if(status==='completed'){gross+=total;paidCount++;if(i%50===2){refunds.push(`R${i+1},${id},${date},${p.price}.00,INR,settled`);refundTotal+=p.price;}}if(i%10===2)support.push(`T${i+1},${id},${i%30===2?'delivery':'product'},closed`);}
 yield {folder:'Sales',name:'orders.csv',body:orders.join('\n')};yield {folder:'Sales',name:'order-items.csv',body:items.join('\n')};yield {folder:'Finance',name:'refunds.csv',body:refunds.join('\n')};yield {folder:'Operations',name:'support.csv',body:support.join('\n')};
 const topics=[
 ['Policies','Returns','Refund requests for incorrect, damaged or spoiled beverage orders must be raised within 48 hours of delivery; unopened merchandise may be returned within 14 days. Approved refunds are recorded in the refunds ledger with status settled. Shipping charges are not refunded.'],
 ['Policies','Privacy','Customer contact data remains local in this demonstration. Customer email addresses use example.com. No external analytics or model service receives vault contents.'],
 ['Operations','Order fulfilment','Completed orders represent fulfilled sales. Pending and cancelled orders do not count toward recognized gross revenue. Fulfilment teams reconcile line items to the order total each day, then prepare beverage batches and assign delivery windows.'],
 ['Operations','Support workflow','Support tickets reference an order ID. Delivery, freshness and product questions are reviewed by the beverage operations team. The corpus contains closed historical tickets, not a live queue.'],
 ['Product','Product portfolio','JuiceShop is a fictional online juice and beverage retailer. These 500 imaginary catalog variants are scenario background, not actual JuiceShop application products. The portfolio spans Cold-pressed juice, Smoothie, Snack, Bundle and Merchandise categories. Prices are denominated in synthetic INR.'],
 ['Customers','Customer segments','The fictional customer base is divided into Retail, Small business and Wholesale segments. Cities in the customer register are Pune, Delhi, Bengaluru and Mumbai.'],
 ['Market','Market assumptions','This demonstration assumes an India-focused online beverage retail business. No external market sizing, competitive research or demand forecast has been ingested. Market growth and acquisition costs are unknown.'],
 ['Finance','Revenue definitions','Gross revenue is the sum of completed order totals. Settled refunds are deducted separately to produce net recorded sales. These figures exclude costs, tax breakdowns, cash timing and profit.'],
 ];
 for(let cycle=0;cycle<5;cycle++)for(const [folder,title,body]of topics)yield{folder,name:`${title.toLowerCase().replaceAll(' ','-')}-${cycle+1}.md`,body:`# ${title}\n\nFictional JuiceShop • Synthetic reference note ${cycle+1}\n\n${body}\n\n## Scope and ownership\nRevision ${cycle+1}. Owner: fictional ${folder} team. Applies only to this fictional JuiceShop scenario corpus, not the actual JuiceShop database or capture facts. This note is a business statement observed in a file, not an independently verified assertion.\n`};
 yield{folder:'Policies',name:'DATA-DICTIONARY.md',body:`# Synthetic corpus data dictionary\n\nVersion: ${SEED_VERSION}. Entirely fictional JuiceShop beverage-business scenario; not actual JuiceShop database records, capture evidence or verified target facts. Deterministic period 2024-10-01 through 2026-09-30 (730 days).\n\n## Tables\norders: 100000 records. order_id unique; customer_id references customers. total in synthetic INR. 90000 completed, 5000 pending, 5000 cancelled.\ncustomers: 20000 unique customers. All emails example.com.\nproducts: 500 unique products, INR prices.\norder-items: 100000 lines; exactly one per order, quantity 1–3. line_total = quantity × unit_price = order total.\nrefunds: 2000 settled partial refunds, each against a completed order.\nsupport: 10000 closed tickets referencing valid orders.\n\n## Expected controls\nCompleted gross INR ${gross}. Settled refunds INR ${refundTotal}. Net recorded sales INR ${gross-refundTotal}. Completed orders ${paidCount}.\n\n## Unknowns\nCosts, margins, tax components, marketing spend, customer consent, causal loss and incident likelihood are not modeled.\n`};
}
