import {promises as fs,createReadStream} from 'node:fs';
import {join,resolve} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {LIMITS,cleanName,extract,inferRole,exportCSV,fail} from './extract.mjs';
import {buildKnowledge,searchKnowledge} from './knowledge.mjs';
import {seedCorpus,SEED_VERSION} from './seed.mjs';
import {extractDocument,OFFICE_LIMITS} from './office-extract.mjs';
const scopeOf=v=>{if(!['demo','uploads'].includes(v??'uploads'))throw fail('Invalid scope.');return v??'uploads';};
const integer=(v,fallback,min,max)=>{if(v===null||v===undefined)return fallback;if(!/^\d+$/.test(String(v)))throw fail('Invalid pagination.');return Math.min(max,Math.max(min,Number(v)));};
async function readBody(req,max){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>max)throw fail('Request exceeds the size limit.',413);chunks.push(chunk);}return Buffer.concat(chunks);}
async function jsonBody(req){if(req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;try{return JSON.parse((await readBody(req,32768)).toString('utf8'));}catch(e){if(e.status)throw e;throw fail('Invalid JSON request.');}}
function send(res,value,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));}
export async function createVaultStore({dataDir}){
 if(!dataDir)throw new Error('dataDir is required');const root=resolve(dataDir);await fs.mkdir(join(root,'objects'),{recursive:true,mode:0o700});let manifest;
 try{manifest=JSON.parse(await fs.readFile(join(root,'manifest.json'),'utf8'));if(manifest.schemaVersion!==1)throw new Error('Unsupported vault manifest version');}catch(e){if(e.code!=='ENOENT')throw e;manifest={schemaVersion:1,snapshotVersion:0,createdAt:new Date().toISOString(),folders:[],files:[],seedVersion:null};}
 let queue=Promise.resolve(),knowledgeCache=new Map(),cache=new Map(),cacheBytes=0;
 const objectPath=(id,suffix)=>{if(!/^[0-9a-f-]{36}$/.test(id))throw fail('Invalid file identifier.');return join(root,'objects',id+suffix);};
 const save=async()=>{manifest.snapshotVersion++;knowledgeCache.clear();const temp=join(root,'manifest.tmp');await fs.writeFile(temp,JSON.stringify(manifest),{mode:0o600});await fs.rename(temp,join(root,'manifest.json'));};
 const mutate=fn=>{const operation=queue.then(fn);queue=operation.catch(()=>{});return operation;};
 const load=async file=>{if(cache.has(file.id))return cache.get(file.id).value;const value=JSON.parse(await fs.readFile(objectPath(file.id,'.index.json'),'utf8'));const weight=file.bytes*4;if(weight<64*1024*1024){while(cacheBytes+weight>64*1024*1024&&cache.size){const [id,v]=cache.entries().next().value;cache.delete(id);cacheBytes-=v.weight;}cache.set(file.id,{value,weight});cacheBytes+=weight;}return value;};
 const get=id=>{const f=manifest.files.find(x=>x.id===id);if(!f)throw fail('File not found.',404);return f;};
 const folder=(id,scope)=>{if(id===null||id===undefined||id==='')return null;const f=manifest.folders.find(x=>x.id===id&&x.scope===scope);if(!f)throw fail('Folder not found in this scope.',404);return f;};
 const importFile=async({name,buffer,scope='uploads',folderId=null,deferSave=false})=>{name=cleanName(name);scope=scopeOf(scope);const parent=folder(folderId,scope);if(manifest.files.length>=LIMITS.files)throw fail('Vault file limit reached.',409);if(manifest.files.reduce((s,f)=>s+f.bytes,0)+buffer.length>LIMITS.storageBytes)throw fail('Local vault capacity reached (512 MiB including trash).',413);const data=await extractDocument(name,buffer),id=randomUUID(),file={id,name,scope,folderId:parent?.id??null,category:parent?.name??'Business documents',bytes:buffer.length,sha256:createHash('sha256').update(buffer).digest('hex'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:data.status,kind:data.kind,rowCount:data.kind==='workbook'?data.sheets.reduce((n,s)=>n+s.rows.length,0):data.rows.length,sheets:data.sheets?.map(s=>({name:s.name,rowCount:s.rows.length,columns:s.columns,headerRow:s.headerRow,role:inferRole(s.columns),sheetState:s.sheetState})),extractor:data.extractor??null,chunkCount:data.chunks.length,columns:data.columns,role:inferRole(data.columns),warnings:data.warnings,deletedAt:null};await fs.writeFile(objectPath(id,'.bin'),buffer,{mode:0o600,flag:'wx'});await fs.writeFile(objectPath(id,'.index.json'),JSON.stringify(data),{mode:0o600,flag:'wx'});manifest.files.push(file);if(!deferSave)await save();return file;};
 return {
 get manifest(){return manifest;},load,get,folder,mutate,
 import:options=>mutate(()=>importFile(options)),
 async seed(){return mutate(async()=>{if(manifest.seedVersion===SEED_VERSION)return;const previous=manifest;manifest={...manifest,files:manifest.files.filter(f=>f.scope!=='demo'),folders:manifest.folders.filter(f=>f.scope!=='demo')};try{for(const name of ['Sales','Finance','Customers','Product','Operations','Market','Policies'])manifest.folders.push({id:randomUUID(),name,scope:'demo',parentId:null});for(const item of seedCorpus())await importFile({name:item.name,buffer:Buffer.from(item.body),scope:'demo',folderId:manifest.folders.find(f=>f.scope==='demo'&&f.name===item.folder).id,deferSave:true});manifest.seedVersion=SEED_VERSION;await save();cache.clear();cacheBytes=0;}catch(e){manifest=previous;throw e;}});},
 async addFolder({name,scope='uploads',parentId=null}){return mutate(async()=>{scope=scopeOf(scope);name=cleanName(name);folder(parentId,scope);if(manifest.folders.length>=500)throw fail('Folder limit reached.');if(manifest.folders.some(f=>f.name===name&&f.parentId===parentId&&f.scope===scope))throw fail('Folder name already exists here.',409);const f={id:randomUUID(),name,scope,parentId};manifest.folders.push(f);await save();return f;});},
 async patch(id,patch){return mutate(async()=>{const original=get(id),file={...original};if(file.scope==='demo')throw fail('Synthetic reference files are read-only. Upload a copy to Your business to edit.',403);if('name'in patch)file.name=cleanName(patch.name);if('folderId'in patch){const parent=folder(patch.folderId,file.scope);file.folderId=parent?.id??null;file.category=parent?.name??'Business documents';}if('deletedAt'in patch)file.deletedAt=patch.deletedAt;if('mapping'in patch){const mapping=patch.mapping;if(!mapping||!['orders','refunds','customers','products','order_items',null].includes(mapping.role)||!mapping.fields||typeof mapping.fields!=='object'||Array.isArray(mapping.fields))throw fail('Invalid field mapping.');const columns=mapping.sheet?file.sheets?.find(s=>s.name===mapping.sheet)?.columns:file.columns;if(!columns)throw fail('Workbook sheet not found.');const expected={orders:['order_id','order_date','customer_id','total','currency','status'],refunds:['refund_id','order_id','refund_amount','currency','status'],customers:['customer_id','email'],products:['product_id','name','price'],order_items:['order_id','product_id','quantity','line_total','currency']};for(const key of expected[mapping.role]??[])if(!columns.includes(mapping.fields[key]))throw fail(`Map required field ${key} to an existing column.`);if(Object.values(mapping.fields).some(c=>!columns.includes(c)))throw fail('Mapping references an unknown column.');if(mapping.sheet){file.sheetMappings={...file.sheetMappings,[mapping.sheet]:{role:mapping.role,fields:mapping.fields}};}else{file.mapping={role:mapping.role,fields:mapping.fields};file.role=mapping.role;}}file.updatedAt=new Date().toISOString();Object.assign(original,file);await save();return file;});},
 async context(scope){scope=scopeOf(scope);const version=manifest.snapshotVersion,key=scope+':'+version;if(knowledgeCache.has(key))return knowledgeCache.get(key);const value=await buildKnowledge(manifest.files.map(f=>({...f})),load,scope,version);if(manifest.snapshotVersion===version)knowledgeCache.set(key,value);return value;},
 async search(scope,q,limit){return searchKnowledge(manifest.files.map(f=>({...f})),load,scopeOf(scope),q,limit);},
 streamOriginal(file,res){res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'});const stream=createReadStream(objectPath(file.id,'.bin'));stream.on('error',()=>res.destroy());stream.pipe(res);}
 };
}
export async function createVaultHandler({dataDir,seedDemo=false}={}){
 const store=await createVaultStore({dataDir});if(seedDemo)await store.seed();
 const handler=async(req,res)=>{
 let url;try{url=new URL(req.url,'http://localhost');}catch{return false;}const path=url.pathname;if(!/^\/api\/(vault|knowledge)(\/|$)/.test(path))return false;
 try{
 if(!['GET','HEAD'].includes(req.method)){
 const origin=req.headers.origin;if(req.headers['sec-fetch-site']==='cross-site'||(origin&&new URL(origin).host!==req.headers.host))throw fail('Cross-origin writes are not accepted.',403);
 }
 const scope=scopeOf(url.searchParams.get('scope')??'uploads');
 if(path==='/api/vault/meta'&&req.method==='GET'){send(res,{snapshotVersion:store.manifest.snapshotVersion,limits:LIMITS,officeLimits:OFFICE_LIMITS,scopes:['uploads','demo'],localOnly:true,extractionSupport:['CSV','TSV','JSON','Markdown','UTF-8 text','XLSX (bounded tables)','DOCX (body text/tables)','PDF (text layer only)'],unsupported:['XLS','DOC','XLSM','DOCM','OCR'],seedVersion:store.manifest.seedVersion});return true;}
 if(path==='/api/vault/folders'){
 if(req.method==='GET'){send(res,{folders:store.manifest.folders.filter(f=>f.scope===scope),snapshotVersion:store.manifest.snapshotVersion});return true;}
 if(req.method==='POST'){const body=await jsonBody(req);if(scope==='demo')throw fail('Demo folders are read-only.',403);send(res,await store.addFolder({...body,scope}),201);return true;}
 }
 if(path==='/api/vault/files'&&req.method==='GET'){
 const q=(url.searchParams.get('q')??'').toLowerCase().slice(0,200),folderId=url.searchParams.get('folder'),trash=url.searchParams.get('trash')==='true',kind=url.searchParams.get('kind'),sort=url.searchParams.get('sort')??'name',offset=integer(url.searchParams.get('offset'),0,0,1000),limit=integer(url.searchParams.get('limit'),50,1,100);
 if(!['name','updated','size','rows'].includes(sort))throw fail('Invalid sort.');let files=store.manifest.files.filter(f=>f.scope===scope&&Boolean(f.deletedAt)===trash&&(!folderId||f.folderId===(folderId==='root'?null:folderId))&&(!kind||f.kind===kind||(kind==='table'&&f.kind==='workbook'))&&(!q||f.name.toLowerCase().includes(q)));
 files.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='updated'?b.updatedAt.localeCompare(a.updatedAt):sort==='size'?b.bytes-a.bytes:b.rowCount-a.rowCount);send(res,{files:files.slice(offset,offset+limit),total:files.length,offset,limit,snapshotVersion:store.manifest.snapshotVersion});return true;
 }
 if(path==='/api/vault/upload'&&req.method==='POST'){
 if(scope==='demo')throw fail('Upload to Your business; synthetic reference is read-only.',403);const name=cleanName(url.searchParams.get('name'));const declared=Number(req.headers['content-length']);if(declared>LIMITS.fileBytes)throw fail('File exceeds 16 MiB.',413);const buffer=Buffer.isBuffer(req.body)?req.body:await readBody(req,LIMITS.fileBytes);send(res,{file:await store.import({name,buffer,scope,folderId:url.searchParams.get('folder')||null}),snapshotVersion:store.manifest.snapshotVersion},201);return true;
 }
 const match=path.match(/^\/api\/vault\/files\/([0-9a-f-]{36})(?:\/(preview|download|export|restore|mapping))?$/);
 if(match){const file=store.get(match[1]),action=match[2];if(req.method==='DELETE'&&!action){send(res,{file:await store.patch(file.id,{deletedAt:new Date().toISOString()})});return true;}if(req.method==='PATCH'&&!action){const b=await jsonBody(req),patch={};if('name'in b)patch.name=b.name;if('folderId'in b)patch.folderId=b.folderId;send(res,{file:await store.patch(file.id,patch)});return true;}if(action==='restore'&&req.method==='POST'){send(res,{file:await store.patch(file.id,{deletedAt:null})});return true;}if(action==='mapping'&&req.method==='POST'){send(res,{file:await store.patch(file.id,{mapping:await jsonBody(req)})});return true;}if(file.deletedAt)throw fail('File is in trash. Restore it to preview.',410);if(req.method==='GET'){
 if(action==='download'){store.streamOriginal(file,res);return true;}const originalData=await store.load(file);const sheetName=url.searchParams.get('sheet');const data=originalData.kind==='workbook'?(sheetName?originalData.sheets.find(s=>s.name===sheetName):originalData.sheets[0]):originalData;if(!data)throw fail('Workbook sheet not found.',404);
 if(action==='export'){if(data.kind!=='table')throw fail('Structured export requires a table.');const format=url.searchParams.get('format')??'json';if(!['json','csv'].includes(format))throw fail('Export format must be json or csv.');res.writeHead(200,{'Content-Type':format==='json'?'application/json':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="vault-table.${format}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(format==='csv'?exportCSV(data):JSON.stringify({snapshotVersion:store.manifest.snapshotVersion,file:{id:file.id,name:file.name,scope:file.scope},sheet:data.name??null,rowNumbers:data.rowNumbers??null,columns:data.columns,rows:data.rows}));return true;}
 if(action==='preview'){const offset=integer(url.searchParams.get('offset'),0,0,LIMITS.rows),limit=integer(url.searchParams.get('limit'),50,1,100);send(res,{file,kind:data.kind,sheet:data.name??null,sheets:originalData.sheets?.map(s=>({name:s.name,rowCount:s.rows.length,headerRow:s.headerRow,sheetState:s.sheetState})),rowNumbers:data.rowNumbers?.slice(offset,offset+limit),columns:data.columns,rows:data.rows.slice(offset,offset+limit),totalRows:data.rows.length,chunks:data.chunks.slice(offset,offset+limit),totalChunks:data.chunks.length,offset,limit,warnings:originalData.warnings,snapshotVersion:store.manifest.snapshotVersion});return true;}
 if(!action){send(res,{file});return true;}
 }}
 if(path==='/api/knowledge/context'&&req.method==='GET'){send(res,await store.context(scope));return true;}
 if((path==='/api/knowledge/search'||path==='/api/knowledge/context/search')&&req.method==='GET'){const q=(url.searchParams.get('q')??'').trim();if(q.length<2||q.length>200)throw fail('Search must contain 2–200 characters.');const version=store.manifest.snapshotVersion;send(res,{query:q,scope,snapshotVersion:version,results:await store.search(scope,q,integer(url.searchParams.get('limit'),20,1,50)),method:'lexical AND matching; exact source excerpts, no LLM synthesis'});return true;}
 send(res,{error:'Vault route or method not found.'},404);
 }catch(e){if(!res.headersSent)send(res,{error:e.status?e.message:'Local vault operation failed.'},e.status??500);else res.destroy();if(!e.status)console.error('Vault operation:',e.message);}return true;
 };handler.store=store;return handler;
}
