import fs from'node:fs/promises';import path from'node:path';
const base='http://127.0.0.1:4317',runId=process.argv.find(x=>x.startsWith('--run='))?.slice(6),execute=process.argv.includes('--execute'),root=new URL('../',import.meta.url).pathname,maxRequests=Number(process.argv.find(x=>x.startsWith('--max-requests='))?.split('=')[1]||81);
async function api(route,body){const r=await fetch(base+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json',Origin:base}:{},body:body?JSON.stringify(body):undefined,redirect:'error',signal:AbortSignal.timeout(body?90000:15000)});let data;try{data=await r.json()}catch{throw Error('Local API did not return JSON')}return{http:r.status,...data}}
if(!/^[a-f0-9-]{36}$/.test(runId??''))throw Error('Supply --run=YOUR_SAVED_RUN_ID.');if(!Number.isInteger(maxRequests)||maxRequests<1||maxRequests>81)throw Error('Request budget must be 1–81.');
const config=await api('/api/workspace/v2/status');if(!config.provider?.ready)throw Error('Configure and review your provider first.');
const {run}=await api('/api/workspace/v2/runs/'+runId);if(!run||!Array.isArray(run.result?.findings))throw Error('Reviewed run/count changed; stop for review.');
const selections=[];for(const finding of run.result.findings){const route='/api/workspace/v2/runs/'+runId+'/findings/'+encodeURIComponent(finding.id)+'/fix',state=await api(route);if(state.http!==200)throw Error('Local cache preflight failed: '+finding.id);selections.push({id:finding.id,route,eligible:state.eligibility?.eligible===true,status:state.cache?.status,historicalCount:state.historicalProposals?.length??0,reason:state.eligibility?.reason??null})}
const eligible=selections.filter(x=>x.eligible);console.log(JSON.stringify({runId,total:selections.length,eligible:eligible.length,blocked:selections.length-eligible.length,historicalAvailable:selections.filter(x=>x.historicalCount>0).length,cacheStates:selections.reduce((a,x)=>(a[x.status??'unknown']=(a[x.status??'unknown']??0)+1,a),{}),maxProviderRequests:maxRequests,maxCompletionTokensPerRequest:7000,concurrency:1,automaticRetries:0,execute,destination:config.provider.endpoint+'chat/completions',deployment:config.provider.deployment,note:'Execution sends public source context and sanitized findings, incurs model usage, never applies patches. Existing historical proposals and terminal cache states are skipped.'}));if(!execute)process.exit(0);if(!process.argv.some(x=>x.startsWith('--max-requests=')))throw Error('Execution requires an explicit --max-requests=N budget. Preview scope first.');
const dir=path.join(root,'.runtime/remediation-bulk'),file=path.join(dir,runId+'.json');await fs.mkdir(dir,{recursive:true,mode:0o700});let job;try{job=JSON.parse(await fs.readFile(file,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;job={schemaVersion:'remediation-bulk-v1',runId,startedAt:new Date().toISOString(),maxProviderRequests:maxRequests,providerRequestsStarted:0,status:'running',items:{}}}
if(job.runId!==runId||job.maxProviderRequests!==maxRequests)throw Error('Saved job differs from approved scope.');async function save(){job.updatedAt=new Date().toISOString();const temp=file+'.tmp';await fs.writeFile(temp,JSON.stringify(job,null,2),{mode:0o600});await fs.rename(temp,file)}
for(const s of selections){if(job.items[s.id]){if(['request-started','request-outcome-unknown','generating'].includes(job.items[s.id].status)){const restored=await api(s.route);if(['proposed','abstained','failed'].includes(restored.cache?.status)){job.items[s.id]={status:restored.cache.status,cached:true,key:restored.cache.key,error:restored.cache.error??null,reconciledAt:new Date().toISOString()};await save();}}continue;}if(!s.eligible){job.items[s.id]={status:'blocked',reason:s.reason};await save();continue}const current=await api(s.route);if(current.historicalProposals?.length&&['missing','stale'].includes(current.cache?.status)){job.items[s.id]={status:'historical-available',cached:true,freshness:'unverified',reason:'Existing historical proposal retained; bulk does not regenerate it automatically.'};await save();continue}if(['proposed','abstained','failed','generating'].includes(current.cache?.status)){job.items[s.id]={status:current.cache.status,cached:true,key:current.cache.key,error:current.cache.error??null};await save();continue}if(job.providerRequestsStarted>=maxRequests)throw Error('Approved request bound reached.');job.items[s.id]={status:'request-started',startedAt:new Date().toISOString()};job.providerRequestsStarted++;await save();try{const result=await api(s.route,{consent:true});job.items[s.id]={status:result.cache?.status??'request-failed',http:result.http,key:result.cache?.key??null,cached:result.cached??false,error:result.cache?.error??result.error??null,finishedAt:new Date().toISOString()};}catch(e){job.items[s.id]={status:'request-outcome-unknown',error:e.name==='TimeoutError'?'Local API wait timed out; inspect durable cache before any explicit retry.':'Local request failed; inspect durable cache.',finishedAt:new Date().toISOString()};await save();throw Error('Stopped after unknown request outcome; no automatic retry.')}await save();console.log(JSON.stringify({done:Object.keys(job.items).length,total:selections.length,findingId:s.id,...job.items[s.id]}));}
job.status=Object.values(job.items).some(x=>['request-started','request-outcome-unknown','generating'].includes(x.status))?'incomplete':'finished';job.counts=Object.values(job.items).reduce((a,x)=>(a[x.status]=(a[x.status]??0)+1,a),{});await save();console.log(JSON.stringify({status:job.status,counts:job.counts,providerRequestsStarted:job.providerRequestsStarted}));
